name: ${project.name}
version: ${project.version}
main: com.i0dev.vouchers.VouchersPlugin
website: ${project.url}
authors: [ i01 ]
depend: [ MassiveCore ]
description: ${project.description}
api-version: 1.20
permissions:
  vouchers.basecommand: { description: vouchers basecommand, default: false }
  vouchers.version: { description: check version, default: false }
  vouchers.*:
    vouchers.basecommand: true
    vouchers.version: true
  vouchers.kit.op:
    default: op
    children:
      vouchers.*: true
  vouchers.kit.rank0:
    default: false
    children:
      vouchers.basecommand: true
  vouchers.kit.default:
    default: true
    children:
      vouchers.kit.rank0: true